var palletBoxKeywords=[
"collapsible bulk containers manufacturers",
"pallet box",
"box pallet",
"plastic box pallets",
"pallet boxes plastic",
"pallet with boxes",
"foldable pallet boxes",
"pallet boxes with lids",
"folding pallet box",
"boxes on a pallet",
"folding plastic pallet boxes",
"palletizing boxes",
"foldable pallet box",
"pallet boxes ireland",
"pallet boxes melbourne",
"fruit pallet box",
"pallet box hire",
"bulk containers plastic",
"plastic bulk storage containers",
"used plastic bulk containers",
"plastic pallet and container",
"used pallet containers",
"pallet containers used",
"pallets and containers",
"box pallet type containers",
"pallet boxes for sale",
"large storage bins",
"collapsible plastic pallet box",
"collapsible pallet boxes plastic",
"pallet crates",
"large plastic pallets",
"large plastic storage bins",
"large plastic bins",
"extra large storage containers",
"pallet storage",
"storage pallets",
"storage pallets plastic",
"plastic bulk boxes",
"bulk buy plastic storage boxes",
"small plastic boxes bulk",
"4 foot plastic storage containers",
"euro pallet boxes",
"bulk container",
"bulk storage containers",
"container bulk",
"bulk shipping containers",
"bulk containers for sale",
"containers in bulk",
"buy containers in bulk",
"folding bulk containers",
"reusable bulk container",
"storage containers in bulk",
"bulk liquid containers",
"storage containers bulk",
"steel bulk containers",
"international bulk container",
"stackable bulk containers",
"metal bulk containers",
"bulk product containers",
"intermodal bulk container",
"liquid bulk containers",
"flexible bulk container",
"bulk cargo containers",
"orbis bulk containers",
"semi bulk container",
"buckhorn bulk containers",
"bulk containers canada",
"bulk container transport",
"bulk in container",
"bulk plastic containers",
"plastic containers bulk",
"bulk plastic bins",
"plastic bulk bins",
"bulk plastic storage containers",
"plastic containers in bulk",
"bulk plastic tubs",
"plastic bulk bins for sale",
"bulk plastic",
"bulk plastic buckets",
"bulk plastic storage bins",
"plastic storage bins bulk",
"plastic bulk",
"buy plastic containers in bulk",
"plastic pails bulk",
"plastic storage containers bulk",
"plastic canisters bulk",
"bulk plastic jars",
"plastic freezer containers bulk",
"plastic food containers bulk",
"bulk plastic food containers",
"buckhorn plastic bulk containers",
"bulk plastic baskets",
"collapsible containers",
"collapsible shipping containers",
"collapsible plastic containers",
"plastic collapsible containers",
"collapsible gaylord containers",
"bulk bins",
"bulk storage bins",
"storage bins in bulk",
"storage bins bulk",
"poly bulk bins",
"bulk bins for sale",
"cheap storage bins bulk",
"cheap storage bins in bulk",
"collapsible bulk containers",
"used collapsible bulk containers",
"plastic collapsible bulk containers",
"collapsible bulk containers used",
"buckhorn collapsible bulk containers",
"bulk boxes",
"bulk plastic boxes",
"bulk plastic storage boxes",
"bulk buy storage boxes",
"bulk storage boxes",
"plastic storage boxes bulk",
"bulk totes",
"bulk storage totes",
"storage totes in bulk",
"bulk plastic totes",
"storage totes bulk",
"buy plastic totes in bulk",
"totes bulk",
"bulk liquid totes",
"bulk oil totes",
"plastic storage boxes",
"large plastic storage boxes",
"plastic box",
"storage boxes plastic",
"large plastic box",
"extra large plastic storage boxes",
"lockable plastic storage box",
"storage containers",
"big storage boxes",
"extra large storage boxes",
"large storage boxes with lids",
"big storage bins",
"commercial storage containers",
"330 gal storage tank",
"plastic pallet boxes",
"plastic pallet boxes with lids",
"pallet box plastic",
"plastic box pallet",
"plastic pallet storage boxes",
"folding pallet boxes",
"pallet storage box",
"used plastic pallet boxes for sale",
"plastic pallet boxes for sale",
"used plastic pallet boxes",
"plastic box pallets for sale",
"pallet bins",
"plastic pallet bins",
"pallet storage bins",
"pallet bins used",
"pallet bin storage",
"pallet bins for sale",
"large storage containers",
"large plastic containers",
"large plastic storage containers",
"large containers",
"large metal storage containers",
"extra large plastic storage containers",
"plastic containers large",
"container plastic storage",
"plastic storage pallets",
"pallet container",
"pallet containers plastic",
"plastic pallet containers",
"container pallet",
"stackable pallet containers",
"pallet storage containers",
"pallets in container",
"plastic storage bins",
"plastic bins",
"collapsible plastic bins",
"plastic bins with lids",
"plastic container bins",
"discount plastic storage bins",
"tote containers",
"bulk tote containers",
"tote plastic container",
"liquid tote containers",
"container totes",
"tote tank",
"plastic tote tanks",
"tote tanks for sale",
"poly tote tanks",
"tank totes",
"300 gallon tote tank",
"tote tank suppliers",
"tote tank volume",
"plastic totes",
"plastic storage totes",
"plastic pallet totes",
"collapsible plastic totes",
"large plastic totes",
"plastic tote boxes",
"plastic tote bins",
"plastic oil totes",
"reusable plastic totes",
"reinforced plastic totes",
"collapsible pallet",
"collapsible pallet boxes",
"collapsible plastic box pallets",
"collapsible pallet containers",
"collapsible pallet bins",
"collapsible plastic pallets",
"collapsible pallet crate",
"bulk plastic containers with lids",
"plastic bulk containers with lids",
"bulk containers with lids",
"plastic containers with lids in bulk",
"bulk storage containers with lids",
"bulk storage bins with lids",
"used bulk containers",
"used bulk containers for sale",
"used bulk bins",
"used bulk bins for sale",
"industrial bulk containers",
"industrial plastic containers",
"industrial bulk container",
"plastic container industry",
"pallet totes",
"plastic folding bulk shipping container",
"used plastic crates for sale",
"plastic pallet crates",
"plastic pallet crates for sale",
"extra large plastic storage containers with lids",
"plastic container lids",
"lidded plastic containers",
"bulk container packaging",
"plastic cargo containers",
"container plastic 1000l",
"plastic containers round",
"plastic garbage containers",
"plastic container ratings",
"plastic bulk containers",
"bulk crates"
]

module.exports = palletBoxKeywords;