var foldingCrates = {
    websites: [
        "https://www.plastic-crate.co.uk/product-category/folding-crate/",
        "https://www.plastic-crate.com/product-category/folding-crate/",
        "https://www.chinacrates.com/product-category/folding-crates/",
        "http://www.joinplastic.com/products/foldableBox/foldablePlasticCrates.php",
        "https://www.palletboxsale.com/product-category/plastic-collapsible-crate/",
        "https://www.cnboxstore.com/product-category/collapsible-crates/",
    ],
    rankedKeywords:[

    ],
    keywords: [
        "collapsible crates",
        "collapsible crate with lid",
        "collapsible plastic storage boxes with lids",
        "foldable plastic storage bins",
        "small collapsible crates",
        "collapsible crate with handles",
        "heavy duty folding storage boxes",
        "strong collapsible crates",
        "stackable folding crate",
        "collapsible storage crate",
        "collapsible storage crates plastic",
        "folding crate",
        "folding plastic crates",
        "folding storage crates",
        "folding crates plastic",
        "plastic folding crate",
        "heavy duty folding crate",
        "32l folding crate",
        "folding plastic crates heavy duty",
        "fold up crates",
        "fold flat crate",
        "folding crate with lid",
        "folding crate manufacturer",
        "snap box folding crate",
        "mainstays folding crate",
        "collapsible containers",
        "plastic collapsible containers",
        "collapsible plastic storage containers",
        "collapsible storage containers",
        "collapsible plastic containers",
        "collapsable containers",
        "used collapsible containers",
        "collapsible storage containers with lids",
        "industrial collapsible containers",
        "the home store collapsible storage container",
        "collapsible storage bins",
        "collapsable storage bins",
        "collapsible bins",
        "collapsable bin",
        "collapsible plastic storage bins",
        "collapsible plastic bins",
        "collapsible bins storage",
        "large collapsible storage bins",
        "collapsible cloth storage bins",
        "plastic collapsible crate",
        "collapsible crates plastic",
        "collapsible crates storage",
        "collapsible plastic storage crates",
        "collapsible plastic crates for storage",
        "collapsible shipping crates",
        "heavy duty collapsible crates",
        "rolling collapsible crate",
        "collapsible rolling crate",
        "schiffmayer plastics corp collapsible crates",
        "collapsible crate for car trunk",
        "kis collapsible crate",
        "collapsible crates australia",
        "plastic storage crates",
        "storage crates",
        "storage crates plastic",
        "crates plastic storage",
        "plastic crates for storage",
        "collapsible boxes plastic",
        "collapsible plastic storage boxes",
        "vented plastic crates ",
        "folding collapsible storage box",
        "collapsible pallet boxes plastic",
        "white collapsible storage box",
        "collapsable box",
        "collapsible plastic boxes",
        "collapsible storage boxes",
        "plastic collapsible boxes",
        "plastic collapsible storage boxes",
        "foldable plastic crates",
        "collapsible storage baskets",
        "collapsible storage tote",
        "polymer logistics collapsible storage",
        "folding storage bins",
        "folding storage boxes plastic",
        "folding plastic storage boxes",
        "folding storage bin",
        "plastic folding storage boxes",
        "fold up storage boxes",
        "fold flat storage boxes",
        "plastic storage boxes with folding lids",
        "fold down storage boxes",
        "fold away storage boxes",
        "folding storage basket",
        "folding storage boxes uk",
        "folding crate on wheels",
        "collapsible crate with wheels",
        "folding crate with wheels",
        "collapsible crate on wheels",
        "vented stackable plastic crates",
        "folding box",
        "plastic folding box",
        "folding box plastic",
        "small folding boxes",
        "folding boxes uk",
        "folding container",
        "folding plastic containers",
        "folding shipping container",
        "4 fold container",
        "foldable bins",
        "foldable crate supplier",
        "plastic mesh containers",
        "foldable storage containers",
        "foldable storage baskets",
        "foldable storage",
        "collapsible plastic",
        "collapsible plastic totes",
        "collapsible storage totes",
        "collapsible plastic basket",
        "folding bin",
        "folding plastic basket",
        "plastic folding basket",
        "collapsible tote",
        "collapsable tote",
        "collapsible plastic crate"
    ]
}
module.exports = foldingCrates;